package src;

public class ShowClientDialog extends javax.swing.JDialog {

    /**
     * Creates new form ShowClientDialog
     */
    public ShowClientDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        showClientName.setText(MenuScreen.name);
        showClientCPF.setText(MenuScreen.cpf);
        showClientEmail.setText(MenuScreen.email);
        showClientPhone.setText(MenuScreen.phone);

        showClientGender.setText(MenuScreen.gender);

        showClientStreet.setText(MenuScreen.street);
        showClientNeighborhood.setText(MenuScreen.neighborhood);
        showClientHouseNumber.setText(MenuScreen.houseNumber);
        showClientCEP.setText(MenuScreen.cep);
        showClientCity.setText(MenuScreen.city);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        showClientCity = new javax.swing.JTextField();
        showClientCEP = new javax.swing.JTextField();
        showClientNeighborhood = new javax.swing.JTextField();
        showClientStreet = new javax.swing.JTextField();
        showClientGender = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showClientCPF = new javax.swing.JTextField();
        showClientName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showClientPhone = new javax.swing.JTextField();
        showClientEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        showClientHouseNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizar cliente");
        setMinimumSize(new java.awt.Dimension(650, 350));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Resumo de cliente");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 650, -1));

        showClientCity.setEditable(false);
        showClientCity.setBackground(new java.awt.Color(214, 217, 223));
        showClientCity.setForeground(new java.awt.Color(0, 0, 0));
        showClientCity.setBorder(null);
        showClientCity.setCaretColor(new java.awt.Color(30, 30, 30));
        showClientCity.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        showClientCity.setFocusable(false);
        showClientCity.setRequestFocusEnabled(false);
        showClientCity.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        showClientCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showClientCityActionPerformed(evt);
            }
        });
        getContentPane().add(showClientCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 200, 35));

        showClientCEP.setEditable(false);
        showClientCEP.setBackground(new java.awt.Color(214, 217, 223));
        showClientCEP.setForeground(new java.awt.Color(0, 0, 0));
        showClientCEP.setBorder(null);
        showClientCEP.setCaretColor(new java.awt.Color(30, 30, 30));
        showClientCEP.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        showClientCEP.setFocusable(false);
        showClientCEP.setRequestFocusEnabled(false);
        showClientCEP.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(showClientCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 120, 35));

        showClientNeighborhood.setEditable(false);
        showClientNeighborhood.setBackground(new java.awt.Color(214, 217, 223));
        showClientNeighborhood.setForeground(new java.awt.Color(0, 0, 0));
        showClientNeighborhood.setBorder(null);
        showClientNeighborhood.setCaretColor(new java.awt.Color(30, 30, 30));
        showClientNeighborhood.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        showClientNeighborhood.setFocusable(false);
        showClientNeighborhood.setRequestFocusEnabled(false);
        showClientNeighborhood.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(showClientNeighborhood, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 100, 35));

        showClientStreet.setEditable(false);
        showClientStreet.setBackground(new java.awt.Color(214, 217, 223));
        showClientStreet.setForeground(new java.awt.Color(0, 0, 0));
        showClientStreet.setBorder(null);
        showClientStreet.setCaretColor(new java.awt.Color(30, 30, 30));
        showClientStreet.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        showClientStreet.setFocusable(false);
        showClientStreet.setRequestFocusEnabled(false);
        showClientStreet.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(showClientStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 200, 35));

        showClientGender.setEditable(false);
        showClientGender.setBackground(new java.awt.Color(214, 217, 223));
        showClientGender.setForeground(new java.awt.Color(0, 0, 0));
        showClientGender.setBorder(null);
        showClientGender.setCaretColor(new java.awt.Color(30, 30, 30));
        showClientGender.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        showClientGender.setFocusable(false);
        showClientGender.setRequestFocusEnabled(false);
        showClientGender.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        showClientGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showClientGenderActionPerformed(evt);
            }
        });
        getContentPane().add(showClientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 90, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("N°");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 35, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bairro:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 120, 50, 35));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CEP:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 35, 35));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cidade:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 200, 60, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rua:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 35, 35));

        showClientCPF.setEditable(false);
        showClientCPF.setBackground(new java.awt.Color(214, 217, 223));
        showClientCPF.setForeground(new java.awt.Color(0, 0, 0));
        showClientCPF.setBorder(null);
        showClientCPF.setCaretColor(new java.awt.Color(30, 30, 30));
        showClientCPF.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        showClientCPF.setFocusable(false);
        showClientCPF.setRequestFocusEnabled(false);
        showClientCPF.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(showClientCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, 35));

        showClientName.setEditable(false);
        showClientName.setBackground(new java.awt.Color(214, 217, 223));
        showClientName.setForeground(new java.awt.Color(0, 0, 0));
        showClientName.setBorder(null);
        showClientName.setCaretColor(new java.awt.Color(30, 30, 30));
        showClientName.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        showClientName.setFocusable(false);
        showClientName.setRequestFocusEnabled(false);
        showClientName.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(showClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 200, 35));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nome:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 80, 50, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 120, 30, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("E-mail:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 160, 50, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Telefone:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 35));

        showClientPhone.setEditable(false);
        showClientPhone.setBackground(new java.awt.Color(214, 217, 223));
        showClientPhone.setForeground(new java.awt.Color(0, 0, 0));
        showClientPhone.setBorder(null);
        showClientPhone.setCaretColor(new java.awt.Color(30, 30, 30));
        showClientPhone.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        showClientPhone.setFocusable(false);
        showClientPhone.setRequestFocusEnabled(false);
        showClientPhone.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        showClientPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showClientPhoneActionPerformed(evt);
            }
        });
        getContentPane().add(showClientPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 150, 35));

        showClientEmail.setEditable(false);
        showClientEmail.setBackground(new java.awt.Color(214, 217, 223));
        showClientEmail.setForeground(new java.awt.Color(0, 0, 0));
        showClientEmail.setBorder(null);
        showClientEmail.setCaretColor(new java.awt.Color(30, 30, 30));
        showClientEmail.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        showClientEmail.setFocusable(false);
        showClientEmail.setRequestFocusEnabled(false);
        showClientEmail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(showClientEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 200, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sexo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 240, 40, 35));

        showClientHouseNumber.setEditable(false);
        showClientHouseNumber.setBackground(new java.awt.Color(214, 217, 223));
        showClientHouseNumber.setForeground(new java.awt.Color(0, 0, 0));
        showClientHouseNumber.setBorder(null);
        showClientHouseNumber.setCaretColor(new java.awt.Color(30, 30, 30));
        showClientHouseNumber.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        showClientHouseNumber.setFocusable(false);
        showClientHouseNumber.setRequestFocusEnabled(false);
        showClientHouseNumber.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        showClientHouseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showClientHouseNumberActionPerformed(evt);
            }
        });
        getContentPane().add(showClientHouseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 50, 35));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showClientCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showClientCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showClientCityActionPerformed

    private void showClientGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showClientGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showClientGenderActionPerformed

    private void showClientPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showClientPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showClientPhoneActionPerformed

    private void showClientHouseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showClientHouseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showClientHouseNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowClientDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShowClientDialog dialog = new ShowClientDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField showClientCEP;
    private javax.swing.JTextField showClientCPF;
    private javax.swing.JTextField showClientCity;
    private javax.swing.JTextField showClientEmail;
    private javax.swing.JTextField showClientGender;
    private javax.swing.JTextField showClientHouseNumber;
    private javax.swing.JTextField showClientName;
    private javax.swing.JTextField showClientNeighborhood;
    private javax.swing.JTextField showClientPhone;
    private javax.swing.JTextField showClientStreet;
    // End of variables declaration//GEN-END:variables
}
